In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

# Load dataset
data = load_iris()
X = data.data
y = data.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [2]:
# Train Decision Tree model
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)

# Make predictions
dt_predictions = dt_model.predict(X_test)


In [3]:
# Calculate confusion matrix
dt_confusion_matrix = confusion_matrix(y_test, dt_predictions)
print("Decision Tree Confusion Matrix:\n", dt_confusion_matrix)

# Calculate precision, recall, and F1-score
dt_precision = precision_score(y_test, dt_predictions, average='weighted')
dt_recall = recall_score(y_test, dt_predictions, average='weighted')
dt_f1_score = f1_score(y_test, dt_predictions, average='weighted')

print(f"Decision Tree Precision: {dt_precision:.2f}")
print(f"Decision Tree Recall: {dt_recall:.2f}")
print(f"Decision Tree F1 Score: {dt_f1_score:.2f}")


Decision Tree Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Decision Tree Precision: 1.00
Decision Tree Recall: 1.00
Decision Tree F1 Score: 1.00


In [4]:
# Train SVM model
svm_model = SVC()
svm_model.fit(X_train, y_train)

# Make predictions
svm_predictions = svm_model.predict(X_test)


In [5]:
# Calculate confusion matrix
svm_confusion_matrix = confusion_matrix(y_test, svm_predictions)
print("SVM Confusion Matrix:\n", svm_confusion_matrix)

# Calculate precision, recall, and F1-score
svm_precision = precision_score(y_test, svm_predictions, average='weighted')
svm_recall = recall_score(y_test, svm_predictions, average='weighted')
svm_f1_score = f1_score(y_test, svm_predictions, average='weighted')

print(f"SVM Precision: {svm_precision:.2f}")
print(f"SVM Recall: {svm_recall:.2f}")
print(f"SVM F1 Score: {svm_f1_score:.2f}")

SVM Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
SVM Precision: 1.00
SVM Recall: 1.00
SVM F1 Score: 1.00
